api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    title: 'API de Bilemo'
    description: 'Depuis cette API vous aurez accès à notre catalogue de produits et vous pourrez aussi stocker vos utilisateurs'
    version: '1.0.0'
    show_webby: false