@startuml cas_d'utilisation
scale 1
Left to right direction
skinparam packageStyle rect
actor Clients

rectangle cas_d'utilisation {
    (Clients) --- (s'authentifier)
    (Clients) -- (creer un compte)

    package Users {
        (Clients) -- (voir la liste de ses utilisateurs)
        (Clients) -- (voir les details d'un de ses utilisateur)
        (Clients) -- (creer un utilisateur)
        (Clients) -- (supprimer un utilisateur)
    }

    package Products {
        (Clients) -- (voir la liste des produits)
        (Clients) -- (voir les détails d'un produit)
    }

    Users .> (s'authentifier):include
    Products .> (s'authentifier):include

    (creer un compte) .> (s'authentifier):extend

    (voir les details d'un de ses utilisateur) ..> (voir la liste de ses utilisateurs):extend

    (creer un utilisateur) .> (voir les details d'un de ses utilisateur):extend
    (supprimer un utilisateur) .> (voir les details d'un de ses utilisateur):extend

}

@enduml