@startuml lister_les_produits

actor Client
boundary Systeme
database BDD

note left of Client: le client doit etre authentifié \n et l'utilisateur doit lui appartenir

Client -> Systeme: afficher les details d'un utilisateurs
Systeme -> BDD: recherche de l'utilisateur
BDD --> Systeme : utilisateur trouvé
Systeme --> Client: Json contenant les details de l'utilisateur demandé

@enduml